### ISSUE TITLE
Disabled dropdowns and buttons don't have dimmed colors

### ISSUE THREAD

**Issue by ardacebi** [Webments/simplistika.css#12]
The disabled dropdowns and buttons should have their affiliated colors in a dimmed state.

## To be done
The button, mini button and dropdown components do not have their affiliated colors when they're in a disabled state. They should have their colors in a dimmed state (opacity).

### Current buttons
<img width="828" alt="Screen Shot 2020-04-29 at 00 55 44" src="https://user-images.githubusercontent.com/17576065/80541635-2b316f00-89b4-11ea-86ac-8742814a7d4a.png">

### Current disabled buttons
<img width="812" alt="Screen Shot 2020-04-29 at 00 55 53" src="https://user-images.githubusercontent.com/17576065/80541645-2ff62300-89b4-11ea-8b37-458b0b15d233.png">

### Current mini buttons
<img width="804" alt="Screen Shot 2020-04-29 at 00 56 18" src="https://user-images.githubusercontent.com/17576065/80541668-3d131200-89b4-11ea-908b-b35739f2e2f3.png">

### Current disabled mini buttons
<img width="840" alt="Screen Shot 2020-04-29 at 00 56 27" src="https://user-images.githubusercontent.com/17576065/80541677-4308f300-89b4-11ea-945f-6fec03332f4c.png">

### Current dropdowns
<img width="895" alt="Screen Shot 2020-04-29 at 00 55 02" src="https://user-images.githubusercontent.com/17576065/80541593-11902780-89b4-11ea-8156-ad7a319320bc.png">

### Current disabled dropdowns
<img width="850" alt="Screen Shot 2020-04-29 at 00 55 15" src="https://user-images.githubusercontent.com/17576065/80541608-194fcc00-89b4-11ea-96c5-ccaca7bfedb7.png">

**Comment by srkn-gndz** [comment]
in general,  disabled button becomes one color in other frameworks

### for example

- [angular buttons](https://material.angular.io/components/button/overview)
- [materializecss](https://materializecss.com/buttons.html)
- [this is the live example](https://stackblitz.com/angular/nnborqpeyxq?file=src%2Fapp%2Fbutton-overview-example.html)
